export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="lambda"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

. "$HOME/.cargo/env"

export EDITOR='nvim'
export VISUAL='nvim'

alias vi=nvim
alias vim=nvim

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(pyenv init -)"' >> ~/.zshrc

